name: Gradle


on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

env:
    BUILD_TYPE: Release

jobs:
    build:
        strategy:
            matrix:
                target: [ Win32, x64 ]
                toolset: [ v143, ClangCL ]
        runs-on: [self-hosted, windows, X64]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v2
              with:
                  distribution: "adopt"
                  java-version: 17
                  cache: "gradle"
                  
            - name: Build libhat.lib
              run: gradlew createRelease

